### ISSUE TITLE
Add Projection

### ISSUE THREAD

**Issue by AstraLuma** [ppb/ppb-vector#171]
Add a projection method.

The simplest implementation seems to be `(a * b.normalize()) * b.normalize()`.

**Comment by nbraud** [comment]
@astronouth7303 Is that supposed to be the projection of `a` on the surface normal to `b`?
'cause that wouldn't be it, I think.

Anyhow, yes, having a projection method seems reasonable to me.

**Comment by astronouth7303** [comment]
No, that would be the projection of `a` onto the vector `b`, not its normal, as per [wikipedia](https://en.wikipedia.org/wiki/Vector_projection).

Although maybe defining a version that operates on the normal make sense? Matches reflect then?

**Comment by nbraud** [comment]
@astronouth7303 Both make sense:
- if we think of projecting and reflecting on surfaces (which makes extra sense in higher dimensions), we definitely want a normal;
- if we think of projecting and reflecting on a line, defining it by a collinear vector also makes sense.

I guess we could have `project_by` (for the projection on a vector's normal) and `project_unto` (the vector's collinear line), and similarly `reflect_by` and `reflect_unto` (and deprecate `reflect`, as the name is ambiguous).

If that's something we agree on (and I'd be happy if we find better names), I'd be happy to make it happen.

**Comment by astronouth7303** [comment]
Higher dimensions is something that's explicitly out of scope?

**Comment by nbraud** [comment]
@astronouth7303 This was a parenthesis specifically because of that: “it's an API which is sensible in 2D, and is the main thing you would want in 3D or above”.  I don't think it's out-of-scope to provide an API that's consistent with what happens in not-2D geometry (lowering cognitive load on users).

**Comment by astronouth7303** [comment]
@pathunstrom any perspective from the teaching/student side?

**Comment by pathunstrom** [comment]
I'm going to ask around, but first thoughts:

`reflect` is there because it's an algorithm I used regularly for physics based games (like Arkanoid clones). I've _never_ needed reflect across a line. So my thought on that is `Vector.reflect` should be the physics based version, and something like `Vector.reflect_across` for the across a line version. (Also I'd prefer `reflect_onto` over `reflect_unto` but neither of those feel accurate to me.)

I need to dig more into projection, another thing I've never needed so need to understand better before I can comment.

**Comment by astronouth7303** [comment]
I realized we might need it because @\eevee was discussing some physics they were doing and one of the steps involved projecting the momentum onto the ground. (They were dealing with momentum going over a hill causing the character to catch some air.)

**Comment by pathunstrom** [comment]
That's a good enough reason to add some kind of projection method, so good even if I don't grok it yet.
